// <auto-generated />
using System;
using BloodDonationDb.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodDonationDb.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BloodDonationDbContext))]
    [Migration("20250214185755_version0007")]
    partial class version0007
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.BloodStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MinimumQuantityReached")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RhFactor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BloodsStock", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4eb21f56-068b-44ca-acfb-815b1c6c79e2"),
                            BloodType = 1,
                            CreateOn = new DateTime(2025, 2, 14, 18, 57, 53, 378, DateTimeKind.Utc).AddTicks(5167),
                            MinimumQuantityReached = true,
                            Quantity = 0,
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("7c5484cd-6ac1-4285-b737-4e15d13d6877"),
                            BloodType = 1,
                            CreateOn = new DateTime(2025, 2, 14, 18, 57, 53, 378, DateTimeKind.Utc).AddTicks(7528),
                            MinimumQuantityReached = true,
                            Quantity = 0,
                            RhFactor = 2
                        },
                        new
                        {
                            Id = new Guid("55c138d4-adab-493c-8405-19595bdbf161"),
                            BloodType = 2,
                            CreateOn = new DateTime(2025, 2, 14, 18, 57, 53, 378, DateTimeKind.Utc).AddTicks(7535),
                            MinimumQuantityReached = true,
                            Quantity = 0,
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("1681bf4b-1d05-422b-8461-38b4e967e172"),
                            BloodType = 2,
                            CreateOn = new DateTime(2025, 2, 14, 18, 57, 53, 378, DateTimeKind.Utc).AddTicks(7537),
                            MinimumQuantityReached = true,
                            Quantity = 0,
                            RhFactor = 2
                        },
                        new
                        {
                            Id = new Guid("5218ec5a-a46a-45dc-a4dc-bce3f91c2712"),
                            BloodType = 4,
                            CreateOn = new DateTime(2025, 2, 14, 18, 57, 53, 378, DateTimeKind.Utc).AddTicks(7539),
                            MinimumQuantityReached = true,
                            Quantity = 0,
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("ae521613-9cc6-4bc5-abe4-32d9dca5e973"),
                            BloodType = 4,
                            CreateOn = new DateTime(2025, 2, 14, 18, 57, 53, 378, DateTimeKind.Utc).AddTicks(7541),
                            MinimumQuantityReached = true,
                            Quantity = 0,
                            RhFactor = 2
                        },
                        new
                        {
                            Id = new Guid("ea216860-45a7-4b29-8768-7909da4206f1"),
                            BloodType = 3,
                            CreateOn = new DateTime(2025, 2, 14, 18, 57, 53, 378, DateTimeKind.Utc).AddTicks(7559),
                            MinimumQuantityReached = true,
                            Quantity = 0,
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("2d1b5075-eb72-47f2-b23e-d94a2602a8b7"),
                            BloodType = 3,
                            CreateOn = new DateTime(2025, 2, 14, 18, 57, 53, 378, DateTimeKind.Utc).AddTicks(7561),
                            MinimumQuantityReached = true,
                            Quantity = 0,
                            RhFactor = 2
                        });
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.DonationDonor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodStockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("BloodStockId");

                    b.HasIndex("DonorId");

                    b.ToTable("DonationDonors", (string)null);
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.DonationReceiver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BloodStockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("BloodStockId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("DonationReceivers", (string)null);
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.Donor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDonor")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDonation")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NextDonation")
                        .HasColumnType("datetime");

                    b.Property<int>("RhFactor")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Donors_Email");

                    b.ToTable("Donors", (string)null);
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.Receiver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RhFactor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Receiver_Email");

                    b.ToTable("Receivers", (string)null);
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BloodDonationDb.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.DonationDonor", b =>
                {
                    b.HasOne("BloodDonationDb.Domain.Entities.BloodStock", "BloodStock")
                        .WithMany("DonationDonors")
                        .HasForeignKey("BloodStockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_BloodStock_DonationDonor");

                    b.HasOne("BloodDonationDb.Domain.Entities.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Donor_Donation_Id");

                    b.Navigation("BloodStock");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.DonationReceiver", b =>
                {
                    b.HasOne("BloodDonationDb.Domain.Entities.BloodStock", "BloodStock")
                        .WithMany("DonationReceivers")
                        .HasForeignKey("BloodStockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_BloodStock_DonationReceiver");

                    b.HasOne("BloodDonationDb.Domain.Entities.Receiver", "Receiver")
                        .WithMany("Donations")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Receiver_Donation_Id");

                    b.Navigation("BloodStock");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.Donor", b =>
                {
                    b.OwnsOne("BloodDonationDb.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("DonorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("ZipCode");

                            b1.HasKey("DonorId");

                            b1.ToTable("Donors");

                            b1.WithOwner()
                                .HasForeignKey("DonorId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.Receiver", b =>
                {
                    b.OwnsOne("BloodDonationDb.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ReceiverId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("ZipCode");

                            b1.HasKey("ReceiverId");

                            b1.ToTable("Receivers");

                            b1.WithOwner()
                                .HasForeignKey("ReceiverId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("BloodDonationDb.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("BloodDonationDb.Domain.Entities.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_RefreshToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.BloodStock", b =>
                {
                    b.Navigation("DonationDonors");

                    b.Navigation("DonationReceivers");
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.Donor", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("BloodDonationDb.Domain.Entities.Receiver", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
