//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationDb.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessageException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessageException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloodDonationDb.Exceptions.ResourceMessageException", typeof(ResourceMessageException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In address, city cannot be empty..
        /// </summary>
        public static string ADDRESS_CITY_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_CITY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In address, country cannot be empty..
        /// </summary>
        public static string ADDRESS_COUNTRY_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_COUNTRY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In address, number cannot be empty..
        /// </summary>
        public static string ADDRESS_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In address, state cannot be empty..
        /// </summary>
        public static string ADDRESS_STATE_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_STATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In address, street cannot be empty..
        /// </summary>
        public static string ADDRESS_STREET_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_STREET_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In address, zip code cannot be empty..
        /// </summary>
        public static string ADDRESS_ZIP_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_ZIP_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date cannot be empty.
        /// </summary>
        public static string BIRTH_DATE_EMPTY {
            get {
                return ResourceManager.GetString("BIRTH_DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date invalid.
        /// </summary>
        public static string BIRTH_DATE_INVALID {
            get {
                return ResourceManager.GetString("BIRTH_DATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth not allowed for donors turning 69.
        /// </summary>
        public static string BIRTH_DATE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("BIRTH_DATE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type not supported.
        /// </summary>
        public static string BLOOD_TYPE_NOT_SUPPOTED {
            get {
                return ResourceManager.GetString("BLOOD_TYPE_NOT_SUPPOTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code not found.
        /// </summary>
        public static string CEP_NOT_FOUND {
            get {
                return ResourceManager.GetString("CEP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation date cannot be empty.
        /// </summary>
        public static string DONATION_DATE_EMPTY {
            get {
                return ResourceManager.GetString("DONATION_DATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The donation date cannot be greater than the current date.
        /// </summary>
        public static string DONATION_DATE_GREATER_CURRENT_DATE {
            get {
                return ResourceManager.GetString("DONATION_DATE_GREATER_CURRENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next donation date for the donor must be from.
        /// </summary>
        public static string DONATION_NOT_ALLOWED_NEXT_DONATION_DATE {
            get {
                return ResourceManager.GetString("DONATION_NOT_ALLOWED_NEXT_DONATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity donat must be between 420 and 470 ml.
        /// </summary>
        public static string DONATION_QUANTITY_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("DONATION_QUANTITY_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor cannot yet make a donation. Donor is under 18 years old..
        /// </summary>
        public static string DONOR_CANNOT_DONATION {
            get {
                return ResourceManager.GetString("DONOR_CANNOT_DONATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor not found.
        /// </summary>
        public static string DONOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("DONOR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered.
        /// </summary>
        public static string EMAIL_ALREADY_REGISTER {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty.
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid.
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and/or password invalid.
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender not supported.
        /// </summary>
        public static string GENDER_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("GENDER_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token was generated for the user.
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long, contain at least 1 digit, at least 1 lowercase letter, at least 1 uppercase letter, and at least 1 special character (!*@#$%^&amp;+=).
        /// </summary>
        public static string PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RH Factor not supported.
        /// </summary>
        public static string RH_FACTOR_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("RH_FACTOR_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server error.
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User without to access resource.
        /// </summary>
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight cannot be less than 50 kg and greater than 140 kg.
        /// </summary>
        public static string WEIGHT_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("WEIGHT_NOT_ALLOWED", resourceCulture);
            }
        }
    }
}
